"""empty message

Revision ID: 198d0aa7dc6d
Revises: d866c9698aa6
Create Date: 2025-10-26 02:54:15.794992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198d0aa7dc6d'
down_revision = 'd866c9698aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vaccination_Schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('vaccination_name', sa.String(), nullable=False),
    sa.Column('vaccination_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Vaccination Schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vaccination Schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('batch_id', sa.INTEGER(), nullable=False),
    sa.Column('vaccination_name', sa.VARCHAR(), nullable=False),
    sa.Column('vaccination_date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Vaccination_Schedule')
    # ### end Alembic commands ###
