"""Another new migration

Revision ID: 1fbc81a4f7f8
Revises: e791172ebe9d
Create Date: 2025-09-27 20:46:04.725788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbc81a4f7f8'
down_revision = 'e791172ebe9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('egg_production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_eggs', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('egg_production', schema=None) as batch_op:
        batch_op.drop_column('extra_eggs')

    # ### end Alembic commands ###
