"""empty message

Revision ID: 3befa52e694e
Revises: 198d0aa7dc6d
Create Date: 2025-10-27 19:05:04.531469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3befa52e694e'
down_revision = '198d0aa7dc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feed_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_name', sa.String(), nullable=False),
    sa.Column('sacks_in_storage', sa.Integer(), nullable=False),
    sa.Column('sacks_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Feed_records')
    # ### end Alembic commands ###
