"""Initial migration

Revision ID: 45be1890a29a
Revises: 
Create Date: 2025-10-07 16:42:42.064331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45be1890a29a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('initial_number', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_salaries', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('include_salaries', sa.Boolean(), nullable=True),
    sa.Column('include_expenses', sa.Boolean(), nullable=True),
    sa.Column('include_transport', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=False),
    sa.Column('quantity_in_crates', sa.Integer(), nullable=False),
    sa.Column('price_per_tray', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transport_costs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crates_in_store', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('egg_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('eggs_collected', sa.Integer(), nullable=False),
    sa.Column('broken_eggs', sa.Integer(), nullable=False),
    sa.Column('remaining_eggs', sa.Integer(), nullable=False),
    sa.Column('quantity_in_crates', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=False),
    sa.Column('extra_eggs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name='fk_batch_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('egg_production')
    op.drop_table('user')
    op.drop_table('stock')
    op.drop_table('sales')
    op.drop_table('profit')
    op.drop_table('expenses')
    op.drop_table('employee_data')
    op.drop_table('batch')
    # ### end Alembic commands ###
