"""empty message

Revision ID: d866c9698aa6
Revises: e7d79f7b6a93
Create Date: 2025-10-26 02:37:05.136313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd866c9698aa6'
down_revision = 'e7d79f7b6a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vaccination Schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('vaccination_name', sa.String(), nullable=False),
    sa.Column('vaccination_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vaccination Schedule')
    # ### end Alembic commands ###
