"""empty message

Revision ID: e7d79f7b6a93
Revises: 4996cd0b2dd8
Create Date: 2025-10-26 01:51:35.009771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d79f7b6a93'
down_revision = '4996cd0b2dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mortality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mortality',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('batch_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('number_of_deaths', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
