"""Another new migration

Revision ID: eaf5dc3469de
Revises: 2448a2688825
Create Date: 2025-09-29 19:44:52.658175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf5dc3469de'
down_revision = '2448a2688825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('egg_production_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('egg_production_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'egg_production', ['egg_production_id'], ['id'])

    # ### end Alembic commands ###
